### ISSUE TITLE
Замечания по lw3

### ISSUE THREAD

**Issue by lulldev** [Nikede/Labs#2]
**Task1:**

1. Вынести повторяющийся код в отдельный класс:
```css
.message_friend {
  width: 345px;
  margin: 17px;
  outline: 1px solid #000;
  float: left;
  white-space: nowrap;
  background: rgb(255, 242, 204);
}

.message_you {
  width: 345px;
  margin: 17px;
  outline: 1px solid #000;
  float: right;
  white-space: nowrap;
  background: #fff;
}
```
2. Форма ввода сообщения должна быты расположена в соответствующем теге `<form>`

**Task2:**

Рассмотрите следующий подход:
- создать рядом "идеальную" БЭМ разметку
- аккуратный перенос стилей на "идеальную" разметку

**Task3:**

1. В html/css отсутствуют классы для мест, стилизация через .row > div не самая лучша идея
2. .row - имя обобщенное и не относящееся к сетке. уточнить имя для сущности, учесть контекст задачи
3. вынести в блок, отступ сделать с помощью css
```html
  Cцена<br>
```
4. элементы мест должны содержаться в классе зала
5. сделать отступы между рядами и местами одинаковыми
